### ISSUE TITLE
Get value from Dictionary

### ISSUE THREAD

**Issue by IvanJosipovic** [IvanJosipovic/JsonPathLINQ#8]
Input JsonPath: ".metadata.annotations.crossplane\\.io/external-name"

Input Data:
```yaml
apiVersion: group.com/v1alpha1
kind: Kind
metadata:
  name: test
  annotations:
    crossplane.io/external-name: app
```

Output Value: app
